// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v4.24.4
// source: liaison.proto

package liaison

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLiaisonServiceCreateEdge = "/LiaisonService/CreateEdge"
const OperationLiaisonServiceDeleteEdge = "/LiaisonService/DeleteEdge"
const OperationLiaisonServiceGetEdge = "/LiaisonService/GetEdge"
const OperationLiaisonServiceListEdges = "/LiaisonService/ListEdges"
const OperationLiaisonServiceUpdateEdge = "/LiaisonService/UpdateEdge"

type LiaisonServiceHTTPServer interface {
	CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error)
	GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error)
	ListEdges(context.Context, *ListEdgesRequest) (*ListEdgesResponse, error)
	UpdateEdge(context.Context, *UpdateEdgeRequest) (*UpdateEdgeResponse, error)
}

func RegisterLiaisonServiceHTTPServer(s *http.Server, srv LiaisonServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/edges", _LiaisonService_CreateEdge0_HTTP_Handler(srv))
	r.GET("/v1/edges/{id}", _LiaisonService_GetEdge0_HTTP_Handler(srv))
	r.GET("/v1/edges", _LiaisonService_ListEdges0_HTTP_Handler(srv))
	r.PUT("/v1/edges/{id}", _LiaisonService_UpdateEdge0_HTTP_Handler(srv))
	r.DELETE("/v1/edges/{id}", _LiaisonService_DeleteEdge0_HTTP_Handler(srv))
}

func _LiaisonService_CreateEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEdgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceCreateEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEdge(ctx, req.(*CreateEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEdgeResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_GetEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEdgeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceGetEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEdge(ctx, req.(*GetEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEdgeResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_ListEdges0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEdgesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceListEdges)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEdges(ctx, req.(*ListEdgesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEdgesResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_UpdateEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEdgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceUpdateEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEdge(ctx, req.(*UpdateEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEdgeResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_DeleteEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEdgeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceDeleteEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEdge(ctx, req.(*DeleteEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEdgeResponse)
		return ctx.Result(200, reply)
	}
}

type LiaisonServiceHTTPClient interface {
	CreateEdge(ctx context.Context, req *CreateEdgeRequest, opts ...http.CallOption) (rsp *CreateEdgeResponse, err error)
	DeleteEdge(ctx context.Context, req *DeleteEdgeRequest, opts ...http.CallOption) (rsp *DeleteEdgeResponse, err error)
	GetEdge(ctx context.Context, req *GetEdgeRequest, opts ...http.CallOption) (rsp *GetEdgeResponse, err error)
	ListEdges(ctx context.Context, req *ListEdgesRequest, opts ...http.CallOption) (rsp *ListEdgesResponse, err error)
	UpdateEdge(ctx context.Context, req *UpdateEdgeRequest, opts ...http.CallOption) (rsp *UpdateEdgeResponse, err error)
}

type LiaisonServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLiaisonServiceHTTPClient(client *http.Client) LiaisonServiceHTTPClient {
	return &LiaisonServiceHTTPClientImpl{client}
}

func (c *LiaisonServiceHTTPClientImpl) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...http.CallOption) (*CreateEdgeResponse, error) {
	var out CreateEdgeResponse
	pattern := "/v1/edges"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceCreateEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...http.CallOption) (*DeleteEdgeResponse, error) {
	var out DeleteEdgeResponse
	pattern := "/v1/edges/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceDeleteEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...http.CallOption) (*GetEdgeResponse, error) {
	var out GetEdgeResponse
	pattern := "/v1/edges/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceGetEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) ListEdges(ctx context.Context, in *ListEdgesRequest, opts ...http.CallOption) (*ListEdgesResponse, error) {
	var out ListEdgesResponse
	pattern := "/v1/edges"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceListEdges))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...http.CallOption) (*UpdateEdgeResponse, error) {
	var out UpdateEdgeResponse
	pattern := "/v1/edges/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceUpdateEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
