// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.31.1
// source: liaison.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLiaisonServiceChangePassword = "/LiaisonService/ChangePassword"
const OperationLiaisonServiceCreateApplication = "/LiaisonService/CreateApplication"
const OperationLiaisonServiceCreateEdge = "/LiaisonService/CreateEdge"
const OperationLiaisonServiceCreateEdgeScanApplicationTask = "/LiaisonService/CreateEdgeScanApplicationTask"
const OperationLiaisonServiceCreateProxy = "/LiaisonService/CreateProxy"
const OperationLiaisonServiceDeleteApplication = "/LiaisonService/DeleteApplication"
const OperationLiaisonServiceDeleteDevice = "/LiaisonService/DeleteDevice"
const OperationLiaisonServiceDeleteEdge = "/LiaisonService/DeleteEdge"
const OperationLiaisonServiceDeleteProxy = "/LiaisonService/DeleteProxy"
const OperationLiaisonServiceGetDevice = "/LiaisonService/GetDevice"
const OperationLiaisonServiceGetEdge = "/LiaisonService/GetEdge"
const OperationLiaisonServiceGetEdgeScanApplicationTask = "/LiaisonService/GetEdgeScanApplicationTask"
const OperationLiaisonServiceGetProfile = "/LiaisonService/GetProfile"
const OperationLiaisonServiceHealth = "/LiaisonService/Health"
const OperationLiaisonServiceListApplications = "/LiaisonService/ListApplications"
const OperationLiaisonServiceListDevices = "/LiaisonService/ListDevices"
const OperationLiaisonServiceListEdges = "/LiaisonService/ListEdges"
const OperationLiaisonServiceListProxies = "/LiaisonService/ListProxies"
const OperationLiaisonServiceListTrafficMetrics = "/LiaisonService/ListTrafficMetrics"
const OperationLiaisonServiceLogin = "/LiaisonService/Login"
const OperationLiaisonServiceLogout = "/LiaisonService/Logout"
const OperationLiaisonServiceUpdateApplication = "/LiaisonService/UpdateApplication"
const OperationLiaisonServiceUpdateDevice = "/LiaisonService/UpdateDevice"
const OperationLiaisonServiceUpdateEdge = "/LiaisonService/UpdateEdge"
const OperationLiaisonServiceUpdateProxy = "/LiaisonService/UpdateProxy"

type LiaisonServiceHTTPServer interface {
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	// CreateApplication 应用
	CreateApplication(context.Context, *CreateApplicationRequest) (*CreateApplicationResponse, error)
	// CreateEdge 边缘
	CreateEdge(context.Context, *CreateEdgeRequest) (*CreateEdgeResponse, error)
	// CreateEdgeScanApplicationTask 任务
	CreateEdgeScanApplicationTask(context.Context, *CreateEdgeScanApplicationTaskRequest) (*CreateEdgeScanApplicationTaskResponse, error)
	CreateProxy(context.Context, *CreateProxyRequest) (*CreateProxyResponse, error)
	DeleteApplication(context.Context, *DeleteApplicationRequest) (*DeleteApplicationResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error)
	DeleteProxy(context.Context, *DeleteProxyRequest) (*DeleteProxyResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	GetEdge(context.Context, *GetEdgeRequest) (*GetEdgeResponse, error)
	GetEdgeScanApplicationTask(context.Context, *GetEdgeScanApplicationTaskRequest) (*GetEdgeScanApplicationTaskResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	// Health 健康检查
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ListApplications(context.Context, *ListApplicationsRequest) (*ListApplicationsResponse, error)
	// ListDevices 设备
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ListEdges(context.Context, *ListEdgesRequest) (*ListEdgesResponse, error)
	// ListProxies 代理
	ListProxies(context.Context, *ListProxiesRequest) (*ListProxiesResponse, error)
	// ListTrafficMetrics 流量监控
	ListTrafficMetrics(context.Context, *ListTrafficMetricsRequest) (*ListTrafficMetricsResponse, error)
	// Login IAM (Identity and Access Management)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	UpdateApplication(context.Context, *UpdateApplicationRequest) (*UpdateApplicationResponse, error)
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error)
	UpdateEdge(context.Context, *UpdateEdgeRequest) (*UpdateEdgeResponse, error)
	UpdateProxy(context.Context, *UpdateProxyRequest) (*UpdateProxyResponse, error)
}

func RegisterLiaisonServiceHTTPServer(s *http.Server, srv LiaisonServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/edges", _LiaisonService_CreateEdge0_HTTP_Handler(srv))
	r.GET("/api/v1/edges/{id}", _LiaisonService_GetEdge0_HTTP_Handler(srv))
	r.GET("/api/v1/edges", _LiaisonService_ListEdges0_HTTP_Handler(srv))
	r.PUT("/api/v1/edges/{id}", _LiaisonService_UpdateEdge0_HTTP_Handler(srv))
	r.DELETE("/api/v1/edges/{id}", _LiaisonService_DeleteEdge0_HTTP_Handler(srv))
	r.GET("/api/v1/devices", _LiaisonService_ListDevices0_HTTP_Handler(srv))
	r.PUT("/api/v1/devices/{id}", _LiaisonService_UpdateDevice0_HTTP_Handler(srv))
	r.GET("/api/v1/devices/{id}", _LiaisonService_GetDevice0_HTTP_Handler(srv))
	r.DELETE("/api/v1/devices/{id}", _LiaisonService_DeleteDevice0_HTTP_Handler(srv))
	r.POST("/api/v1/applications", _LiaisonService_CreateApplication0_HTTP_Handler(srv))
	r.GET("/api/v1/applications", _LiaisonService_ListApplications0_HTTP_Handler(srv))
	r.PUT("/api/v1/applications/{id}", _LiaisonService_UpdateApplication0_HTTP_Handler(srv))
	r.DELETE("/api/v1/applications/{id}", _LiaisonService_DeleteApplication0_HTTP_Handler(srv))
	r.GET("/api/v1/proxies", _LiaisonService_ListProxies0_HTTP_Handler(srv))
	r.POST("/api/v1/proxies", _LiaisonService_CreateProxy0_HTTP_Handler(srv))
	r.PUT("/api/v1/proxies/{id}", _LiaisonService_UpdateProxy0_HTTP_Handler(srv))
	r.DELETE("/api/v1/proxies/{id}", _LiaisonService_DeleteProxy0_HTTP_Handler(srv))
	r.POST("/api/v1/edges/{edge_id}/scan_application_tasks", _LiaisonService_CreateEdgeScanApplicationTask0_HTTP_Handler(srv))
	r.GET("/api/v1/edges/{edge_id}/scan_application_tasks", _LiaisonService_GetEdgeScanApplicationTask0_HTTP_Handler(srv))
	r.POST("/api/v1/iam/login", _LiaisonService_Login0_HTTP_Handler(srv))
	r.POST("/api/v1/iam/logout", _LiaisonService_Logout0_HTTP_Handler(srv))
	r.GET("/api/v1/iam/profile", _LiaisonService_GetProfile0_HTTP_Handler(srv))
	r.POST("/api/v1/iam/password", _LiaisonService_ChangePassword0_HTTP_Handler(srv))
	r.GET("/api/health", _LiaisonService_Health0_HTTP_Handler(srv))
	r.GET("/api/v1/traffic-metrics", _LiaisonService_ListTrafficMetrics0_HTTP_Handler(srv))
}

func _LiaisonService_CreateEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEdgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceCreateEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEdge(ctx, req.(*CreateEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEdgeResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_GetEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEdgeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceGetEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEdge(ctx, req.(*GetEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEdgeResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_ListEdges0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEdgesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceListEdges)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEdges(ctx, req.(*ListEdgesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListEdgesResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_UpdateEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEdgeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceUpdateEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEdge(ctx, req.(*UpdateEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEdgeResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_DeleteEdge0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEdgeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceDeleteEdge)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEdge(ctx, req.(*DeleteEdgeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteEdgeResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_ListDevices0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDevicesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceListDevices)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDevices(ctx, req.(*ListDevicesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDevicesResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_UpdateDevice0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDeviceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceUpdateDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDevice(ctx, req.(*UpdateDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateDeviceResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_GetDevice0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeviceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceGetDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDevice(ctx, req.(*GetDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeviceResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_DeleteDevice0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteDeviceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceDeleteDevice)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteDevice(ctx, req.(*DeleteDeviceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteDeviceResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_CreateApplication0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceCreateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApplication(ctx, req.(*CreateApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateApplicationResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_ListApplications0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListApplicationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceListApplications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListApplications(ctx, req.(*ListApplicationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListApplicationsResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_UpdateApplication0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceUpdateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateApplication(ctx, req.(*UpdateApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateApplicationResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_DeleteApplication0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteApplicationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceDeleteApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteApplication(ctx, req.(*DeleteApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteApplicationResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_ListProxies0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProxiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceListProxies)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProxies(ctx, req.(*ListProxiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProxiesResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_CreateProxy0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProxyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceCreateProxy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProxy(ctx, req.(*CreateProxyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProxyResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_UpdateProxy0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProxyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceUpdateProxy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProxy(ctx, req.(*UpdateProxyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProxyResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_DeleteProxy0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteProxyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceDeleteProxy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProxy(ctx, req.(*DeleteProxyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteProxyResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_CreateEdgeScanApplicationTask0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEdgeScanApplicationTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceCreateEdgeScanApplicationTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEdgeScanApplicationTask(ctx, req.(*CreateEdgeScanApplicationTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateEdgeScanApplicationTaskResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_GetEdgeScanApplicationTask0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEdgeScanApplicationTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceGetEdgeScanApplicationTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEdgeScanApplicationTask(ctx, req.(*GetEdgeScanApplicationTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEdgeScanApplicationTaskResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_Login0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_Logout0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_GetProfile0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProfileRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceGetProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProfile(ctx, req.(*GetProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_ChangePassword0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChangePasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceChangePassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ChangePassword(ctx, req.(*ChangePasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChangePasswordResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_Health0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*HealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthResponse)
		return ctx.Result(200, reply)
	}
}

func _LiaisonService_ListTrafficMetrics0_HTTP_Handler(srv LiaisonServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTrafficMetricsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLiaisonServiceListTrafficMetrics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTrafficMetrics(ctx, req.(*ListTrafficMetricsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTrafficMetricsResponse)
		return ctx.Result(200, reply)
	}
}

type LiaisonServiceHTTPClient interface {
	ChangePassword(ctx context.Context, req *ChangePasswordRequest, opts ...http.CallOption) (rsp *ChangePasswordResponse, err error)
	// CreateApplication 应用
	CreateApplication(ctx context.Context, req *CreateApplicationRequest, opts ...http.CallOption) (rsp *CreateApplicationResponse, err error)
	// CreateEdge 边缘
	CreateEdge(ctx context.Context, req *CreateEdgeRequest, opts ...http.CallOption) (rsp *CreateEdgeResponse, err error)
	// CreateEdgeScanApplicationTask 任务
	CreateEdgeScanApplicationTask(ctx context.Context, req *CreateEdgeScanApplicationTaskRequest, opts ...http.CallOption) (rsp *CreateEdgeScanApplicationTaskResponse, err error)
	CreateProxy(ctx context.Context, req *CreateProxyRequest, opts ...http.CallOption) (rsp *CreateProxyResponse, err error)
	DeleteApplication(ctx context.Context, req *DeleteApplicationRequest, opts ...http.CallOption) (rsp *DeleteApplicationResponse, err error)
	DeleteDevice(ctx context.Context, req *DeleteDeviceRequest, opts ...http.CallOption) (rsp *DeleteDeviceResponse, err error)
	DeleteEdge(ctx context.Context, req *DeleteEdgeRequest, opts ...http.CallOption) (rsp *DeleteEdgeResponse, err error)
	DeleteProxy(ctx context.Context, req *DeleteProxyRequest, opts ...http.CallOption) (rsp *DeleteProxyResponse, err error)
	GetDevice(ctx context.Context, req *GetDeviceRequest, opts ...http.CallOption) (rsp *GetDeviceResponse, err error)
	GetEdge(ctx context.Context, req *GetEdgeRequest, opts ...http.CallOption) (rsp *GetEdgeResponse, err error)
	GetEdgeScanApplicationTask(ctx context.Context, req *GetEdgeScanApplicationTaskRequest, opts ...http.CallOption) (rsp *GetEdgeScanApplicationTaskResponse, err error)
	GetProfile(ctx context.Context, req *GetProfileRequest, opts ...http.CallOption) (rsp *GetProfileResponse, err error)
	// Health 健康检查
	Health(ctx context.Context, req *HealthRequest, opts ...http.CallOption) (rsp *HealthResponse, err error)
	ListApplications(ctx context.Context, req *ListApplicationsRequest, opts ...http.CallOption) (rsp *ListApplicationsResponse, err error)
	// ListDevices 设备
	ListDevices(ctx context.Context, req *ListDevicesRequest, opts ...http.CallOption) (rsp *ListDevicesResponse, err error)
	ListEdges(ctx context.Context, req *ListEdgesRequest, opts ...http.CallOption) (rsp *ListEdgesResponse, err error)
	// ListProxies 代理
	ListProxies(ctx context.Context, req *ListProxiesRequest, opts ...http.CallOption) (rsp *ListProxiesResponse, err error)
	// ListTrafficMetrics 流量监控
	ListTrafficMetrics(ctx context.Context, req *ListTrafficMetricsRequest, opts ...http.CallOption) (rsp *ListTrafficMetricsResponse, err error)
	// Login IAM (Identity and Access Management)
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginResponse, err error)
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutResponse, err error)
	UpdateApplication(ctx context.Context, req *UpdateApplicationRequest, opts ...http.CallOption) (rsp *UpdateApplicationResponse, err error)
	UpdateDevice(ctx context.Context, req *UpdateDeviceRequest, opts ...http.CallOption) (rsp *UpdateDeviceResponse, err error)
	UpdateEdge(ctx context.Context, req *UpdateEdgeRequest, opts ...http.CallOption) (rsp *UpdateEdgeResponse, err error)
	UpdateProxy(ctx context.Context, req *UpdateProxyRequest, opts ...http.CallOption) (rsp *UpdateProxyResponse, err error)
}

type LiaisonServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLiaisonServiceHTTPClient(client *http.Client) LiaisonServiceHTTPClient {
	return &LiaisonServiceHTTPClientImpl{client}
}

func (c *LiaisonServiceHTTPClientImpl) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...http.CallOption) (*ChangePasswordResponse, error) {
	var out ChangePasswordResponse
	pattern := "/api/v1/iam/password"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceChangePassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateApplication 应用
func (c *LiaisonServiceHTTPClientImpl) CreateApplication(ctx context.Context, in *CreateApplicationRequest, opts ...http.CallOption) (*CreateApplicationResponse, error) {
	var out CreateApplicationResponse
	pattern := "/api/v1/applications"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceCreateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateEdge 边缘
func (c *LiaisonServiceHTTPClientImpl) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...http.CallOption) (*CreateEdgeResponse, error) {
	var out CreateEdgeResponse
	pattern := "/api/v1/edges"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceCreateEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateEdgeScanApplicationTask 任务
func (c *LiaisonServiceHTTPClientImpl) CreateEdgeScanApplicationTask(ctx context.Context, in *CreateEdgeScanApplicationTaskRequest, opts ...http.CallOption) (*CreateEdgeScanApplicationTaskResponse, error) {
	var out CreateEdgeScanApplicationTaskResponse
	pattern := "/api/v1/edges/{edge_id}/scan_application_tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceCreateEdgeScanApplicationTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) CreateProxy(ctx context.Context, in *CreateProxyRequest, opts ...http.CallOption) (*CreateProxyResponse, error) {
	var out CreateProxyResponse
	pattern := "/api/v1/proxies"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceCreateProxy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) DeleteApplication(ctx context.Context, in *DeleteApplicationRequest, opts ...http.CallOption) (*DeleteApplicationResponse, error) {
	var out DeleteApplicationResponse
	pattern := "/api/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceDeleteApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...http.CallOption) (*DeleteDeviceResponse, error) {
	var out DeleteDeviceResponse
	pattern := "/api/v1/devices/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceDeleteDevice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...http.CallOption) (*DeleteEdgeResponse, error) {
	var out DeleteEdgeResponse
	pattern := "/api/v1/edges/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceDeleteEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) DeleteProxy(ctx context.Context, in *DeleteProxyRequest, opts ...http.CallOption) (*DeleteProxyResponse, error) {
	var out DeleteProxyResponse
	pattern := "/api/v1/proxies/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceDeleteProxy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...http.CallOption) (*GetDeviceResponse, error) {
	var out GetDeviceResponse
	pattern := "/api/v1/devices/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceGetDevice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) GetEdge(ctx context.Context, in *GetEdgeRequest, opts ...http.CallOption) (*GetEdgeResponse, error) {
	var out GetEdgeResponse
	pattern := "/api/v1/edges/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceGetEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) GetEdgeScanApplicationTask(ctx context.Context, in *GetEdgeScanApplicationTaskRequest, opts ...http.CallOption) (*GetEdgeScanApplicationTaskResponse, error) {
	var out GetEdgeScanApplicationTaskResponse
	pattern := "/api/v1/edges/{edge_id}/scan_application_tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceGetEdgeScanApplicationTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...http.CallOption) (*GetProfileResponse, error) {
	var out GetProfileResponse
	pattern := "/api/v1/iam/profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceGetProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Health 健康检查
func (c *LiaisonServiceHTTPClientImpl) Health(ctx context.Context, in *HealthRequest, opts ...http.CallOption) (*HealthResponse, error) {
	var out HealthResponse
	pattern := "/api/health"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceHealth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) ListApplications(ctx context.Context, in *ListApplicationsRequest, opts ...http.CallOption) (*ListApplicationsResponse, error) {
	var out ListApplicationsResponse
	pattern := "/api/v1/applications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceListApplications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListDevices 设备
func (c *LiaisonServiceHTTPClientImpl) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...http.CallOption) (*ListDevicesResponse, error) {
	var out ListDevicesResponse
	pattern := "/api/v1/devices"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceListDevices))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) ListEdges(ctx context.Context, in *ListEdgesRequest, opts ...http.CallOption) (*ListEdgesResponse, error) {
	var out ListEdgesResponse
	pattern := "/api/v1/edges"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceListEdges))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProxies 代理
func (c *LiaisonServiceHTTPClientImpl) ListProxies(ctx context.Context, in *ListProxiesRequest, opts ...http.CallOption) (*ListProxiesResponse, error) {
	var out ListProxiesResponse
	pattern := "/api/v1/proxies"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceListProxies))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTrafficMetrics 流量监控
func (c *LiaisonServiceHTTPClientImpl) ListTrafficMetrics(ctx context.Context, in *ListTrafficMetricsRequest, opts ...http.CallOption) (*ListTrafficMetricsResponse, error) {
	var out ListTrafficMetricsResponse
	pattern := "/api/v1/traffic-metrics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLiaisonServiceListTrafficMetrics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Login IAM (Identity and Access Management)
func (c *LiaisonServiceHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginResponse, error) {
	var out LoginResponse
	pattern := "/api/v1/iam/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutResponse, error) {
	var out LogoutResponse
	pattern := "/api/v1/iam/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) UpdateApplication(ctx context.Context, in *UpdateApplicationRequest, opts ...http.CallOption) (*UpdateApplicationResponse, error) {
	var out UpdateApplicationResponse
	pattern := "/api/v1/applications/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceUpdateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...http.CallOption) (*UpdateDeviceResponse, error) {
	var out UpdateDeviceResponse
	pattern := "/api/v1/devices/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceUpdateDevice))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) UpdateEdge(ctx context.Context, in *UpdateEdgeRequest, opts ...http.CallOption) (*UpdateEdgeResponse, error) {
	var out UpdateEdgeResponse
	pattern := "/api/v1/edges/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceUpdateEdge))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *LiaisonServiceHTTPClientImpl) UpdateProxy(ctx context.Context, in *UpdateProxyRequest, opts ...http.CallOption) (*UpdateProxyResponse, error) {
	var out UpdateProxyResponse
	pattern := "/api/v1/proxies/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLiaisonServiceUpdateProxy))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
