// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: liaison.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 边缘
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Online        int32                  `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_liaison_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{0}
}

func (x *Edge) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Edge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Edge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Edge) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Edge) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *Edge) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Edge) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Edges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edges) Reset() {
	*x = Edges{}
	mi := &file_liaison_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edges) ProtoMessage() {}

func (x *Edges) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edges.ProtoReflect.Descriptor instead.
func (*Edges) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{1}
}

func (x *Edges) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Edges) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type AccessKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_liaison_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKey.ProtoReflect.Descriptor instead.
func (*AccessKey) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{2}
}

func (x *AccessKey) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *AccessKey) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

// 创建边缘节点请求
type CreateEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeRequest) Reset() {
	*x = CreateEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeRequest) ProtoMessage() {}

func (x *CreateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEdgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEdgeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AccessKey             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeResponse) Reset() {
	*x = CreateEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeResponse) ProtoMessage() {}

func (x *CreateEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeResponse.ProtoReflect.Descriptor instead.
func (*CreateEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateEdgeResponse) GetData() *AccessKey {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取边缘节点请求
type GetEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeRequest) Reset() {
	*x = GetEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeRequest) ProtoMessage() {}

func (x *GetEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeRequest.ProtoReflect.Descriptor instead.
func (*GetEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{5}
}

func (x *GetEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Edge                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeResponse) Reset() {
	*x = GetEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeResponse) ProtoMessage() {}

func (x *GetEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeResponse.ProtoReflect.Descriptor instead.
func (*GetEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{6}
}

func (x *GetEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEdgeResponse) GetData() *Edge {
	if x != nil {
		return x.Data
	}
	return nil
}

// 列举边缘节点请求
type ListEdgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEdgesRequest) Reset() {
	*x = ListEdgesRequest{}
	mi := &file_liaison_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEdgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEdgesRequest) ProtoMessage() {}

func (x *ListEdgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEdgesRequest.ProtoReflect.Descriptor instead.
func (*ListEdgesRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{7}
}

func (x *ListEdgesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEdgesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEdgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Edges                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEdgesResponse) Reset() {
	*x = ListEdgesResponse{}
	mi := &file_liaison_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEdgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEdgesResponse) ProtoMessage() {}

func (x *ListEdgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEdgesResponse.ProtoReflect.Descriptor instead.
func (*ListEdgesResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{8}
}

func (x *ListEdgesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListEdgesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListEdgesResponse) GetData() *Edges {
	if x != nil {
		return x.Data
	}
	return nil
}

// 更新边缘节点请求
type UpdateEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 1: running, 2: stopped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEdgeRequest) Reset() {
	*x = UpdateEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEdgeRequest) ProtoMessage() {}

func (x *UpdateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEdgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEdgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEdgeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEdgeRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Edge                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEdgeResponse) Reset() {
	*x = UpdateEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEdgeResponse) ProtoMessage() {}

func (x *UpdateEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEdgeResponse.ProtoReflect.Descriptor instead.
func (*UpdateEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateEdgeResponse) GetData() *Edge {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除边缘节点请求
type DeleteEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeRequest) Reset() {
	*x = DeleteEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeRequest) ProtoMessage() {}

func (x *DeleteEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeResponse) Reset() {
	*x = DeleteEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeResponse) ProtoMessage() {}

func (x *DeleteEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 设备
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Cpu           int32                  `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int32                  `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk          int32                  `protobuf:"varint,6,opt,name=disk,proto3" json:"disk,omitempty"`
	Os            string                 `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_liaison_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{13}
}

func (x *Device) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Device) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Device) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Device) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *Device) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Device) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Device) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Device) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Devices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Devices       []*Device              `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Devices) Reset() {
	*x = Devices{}
	mi := &file_liaison_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Devices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Devices) ProtoMessage() {}

func (x *Devices) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Devices.ProtoReflect.Descriptor instead.
func (*Devices) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{14}
}

func (x *Devices) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Devices) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

// 获取设备请求
type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_liaison_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeviceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Device                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_liaison_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeviceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetDeviceResponse) GetData() *Device {
	if x != nil {
		return x.Data
	}
	return nil
}

// 列举设备请求
type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_liaison_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{17}
}

func (x *ListDevicesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDevicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Devices               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_liaison_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{18}
}

func (x *ListDevicesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListDevicesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListDevicesResponse) GetData() *Devices {
	if x != nil {
		return x.Data
	}
	return nil
}

// 更新设备请求
type UpdateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_liaison_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateDeviceRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDeviceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Device                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_liaison_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateDeviceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateDeviceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateDeviceResponse) GetData() *Device {
	if x != nil {
		return x.Data
	}
	return nil
}

// 应用
type Application struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId        uint64                 `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Port            int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	ApplicationType string                 `protobuf:"bytes,5,opt,name=application_type,json=applicationType,proto3" json:"application_type,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_liaison_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{21}
}

func (x *Application) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Application) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Application) GetApplicationType() string {
	if x != nil {
		return x.ApplicationType
	}
	return ""
}

func (x *Application) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Application) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Applications struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Applications  []*Application         `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Applications) Reset() {
	*x = Applications{}
	mi := &file_liaison_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Applications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Applications) ProtoMessage() {}

func (x *Applications) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Applications.ProtoReflect.Descriptor instead.
func (*Applications) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{22}
}

func (x *Applications) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Applications) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

// 列举应用请求
type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DeviceId      uint64                 `protobuf:"varint,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_liaison_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{23}
}

func (x *ListApplicationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListApplicationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListApplicationsRequest) GetDeviceId() uint64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Applications          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_liaison_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{24}
}

func (x *ListApplicationsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListApplicationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListApplicationsResponse) GetData() *Applications {
	if x != nil {
		return x.Data
	}
	return nil
}

// 更新应用请求
type UpdateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_liaison_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateApplicationRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateApplicationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Application           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationResponse) Reset() {
	*x = UpdateApplicationResponse{}
	mi := &file_liaison_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationResponse) ProtoMessage() {}

func (x *UpdateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateApplicationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateApplicationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateApplicationResponse) GetData() *Application {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除应用请求
type DeleteApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_liaison_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteApplicationRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationResponse) Reset() {
	*x = DeleteApplicationResponse{}
	mi := &file_liaison_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationResponse) ProtoMessage() {}

func (x *DeleteApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteApplicationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteApplicationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 代理
type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicationId uint64                 `protobuf:"varint,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_liaison_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{29}
}

func (x *Proxy) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Proxy) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *Proxy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Proxy) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Proxy) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Proxy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Proxy) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Proxy) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Proxies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Proxies       []*Proxy               `protobuf:"bytes,2,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxies) Reset() {
	*x = Proxies{}
	mi := &file_liaison_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxies) ProtoMessage() {}

func (x *Proxies) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxies.ProtoReflect.Descriptor instead.
func (*Proxies) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{30}
}

func (x *Proxies) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Proxies) GetProxies() []*Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

// 列举代理请求
type ListProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesRequest) Reset() {
	*x = ListProxiesRequest{}
	mi := &file_liaison_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesRequest) ProtoMessage() {}

func (x *ListProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesRequest.ProtoReflect.Descriptor instead.
func (*ListProxiesRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{31}
}

func (x *ListProxiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProxiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Proxies               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesResponse) Reset() {
	*x = ListProxiesResponse{}
	mi := &file_liaison_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesResponse) ProtoMessage() {}

func (x *ListProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesResponse.ProtoReflect.Descriptor instead.
func (*ListProxiesResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{32}
}

func (x *ListProxiesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListProxiesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListProxiesResponse) GetData() *Proxies {
	if x != nil {
		return x.Data
	}
	return nil
}

// 创建代理请求
type CreateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId uint64                 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxyRequest) Reset() {
	*x = CreateProxyRequest{}
	mi := &file_liaison_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxyRequest) ProtoMessage() {}

func (x *CreateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxyRequest.ProtoReflect.Descriptor instead.
func (*CreateProxyRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{33}
}

func (x *CreateProxyRequest) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *CreateProxyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateProxyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Proxy                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProxyResponse) Reset() {
	*x = CreateProxyResponse{}
	mi := &file_liaison_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProxyResponse) ProtoMessage() {}

func (x *CreateProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProxyResponse.ProtoReflect.Descriptor instead.
func (*CreateProxyResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{34}
}

func (x *CreateProxyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateProxyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateProxyResponse) GetData() *Proxy {
	if x != nil {
		return x.Data
	}
	return nil
}

// 更新代理请求
type UpdateProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyRequest) Reset() {
	*x = UpdateProxyRequest{}
	mi := &file_liaison_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyRequest) ProtoMessage() {}

func (x *UpdateProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyRequest.ProtoReflect.Descriptor instead.
func (*UpdateProxyRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateProxyRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProxyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProxyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpdateProxyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateProxyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Proxy                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProxyResponse) Reset() {
	*x = UpdateProxyResponse{}
	mi := &file_liaison_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxyResponse) ProtoMessage() {}

func (x *UpdateProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxyResponse.ProtoReflect.Descriptor instead.
func (*UpdateProxyResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateProxyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateProxyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProxyResponse) GetData() *Proxy {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除代理请求
type DeleteProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxyRequest) Reset() {
	*x = DeleteProxyRequest{}
	mi := &file_liaison_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxyRequest) ProtoMessage() {}

func (x *DeleteProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxyRequest.ProtoReflect.Descriptor instead.
func (*DeleteProxyRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{37}
}

func (x *DeleteProxyRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProxyResponse) Reset() {
	*x = DeleteProxyResponse{}
	mi := &file_liaison_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProxyResponse) ProtoMessage() {}

func (x *DeleteProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProxyResponse.ProtoReflect.Descriptor instead.
func (*DeleteProxyResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{38}
}

func (x *DeleteProxyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteProxyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 任务
type EdgeScanApplicationTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EdgeId        uint64                 `protobuf:"varint,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	TaskStatus    string                 `protobuf:"bytes,3,opt,name=task_status,json=taskStatus,proto3" json:"task_status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Applications  []string               `protobuf:"bytes,6,rep,name=applications,proto3" json:"applications,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeScanApplicationTask) Reset() {
	*x = EdgeScanApplicationTask{}
	mi := &file_liaison_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeScanApplicationTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeScanApplicationTask) ProtoMessage() {}

func (x *EdgeScanApplicationTask) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeScanApplicationTask.ProtoReflect.Descriptor instead.
func (*EdgeScanApplicationTask) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{39}
}

func (x *EdgeScanApplicationTask) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EdgeScanApplicationTask) GetEdgeId() uint64 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

func (x *EdgeScanApplicationTask) GetTaskStatus() string {
	if x != nil {
		return x.TaskStatus
	}
	return ""
}

func (x *EdgeScanApplicationTask) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EdgeScanApplicationTask) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *EdgeScanApplicationTask) GetApplications() []string {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *EdgeScanApplicationTask) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 创建扫描应用任务
type CreateEdgeScanApplicationTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        uint64                 `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeScanApplicationTaskRequest) Reset() {
	*x = CreateEdgeScanApplicationTaskRequest{}
	mi := &file_liaison_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeScanApplicationTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeScanApplicationTaskRequest) ProtoMessage() {}

func (x *CreateEdgeScanApplicationTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeScanApplicationTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeScanApplicationTaskRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{40}
}

func (x *CreateEdgeScanApplicationTaskRequest) GetEdgeId() uint64 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

type CreateEdgeScanApplicationTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeScanApplicationTaskResponse) Reset() {
	*x = CreateEdgeScanApplicationTaskResponse{}
	mi := &file_liaison_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeScanApplicationTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeScanApplicationTaskResponse) ProtoMessage() {}

func (x *CreateEdgeScanApplicationTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeScanApplicationTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateEdgeScanApplicationTaskResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{41}
}

func (x *CreateEdgeScanApplicationTaskResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateEdgeScanApplicationTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取扫描应用任务
type GetEdgeScanApplicationTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeId        uint64                 `protobuf:"varint,1,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeScanApplicationTaskRequest) Reset() {
	*x = GetEdgeScanApplicationTaskRequest{}
	mi := &file_liaison_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeScanApplicationTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeScanApplicationTaskRequest) ProtoMessage() {}

func (x *GetEdgeScanApplicationTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeScanApplicationTaskRequest.ProtoReflect.Descriptor instead.
func (*GetEdgeScanApplicationTaskRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{42}
}

func (x *GetEdgeScanApplicationTaskRequest) GetEdgeId() uint64 {
	if x != nil {
		return x.EdgeId
	}
	return 0
}

type GetEdgeScanApplicationTaskResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          int32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *EdgeScanApplicationTask `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeScanApplicationTaskResponse) Reset() {
	*x = GetEdgeScanApplicationTaskResponse{}
	mi := &file_liaison_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeScanApplicationTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeScanApplicationTaskResponse) ProtoMessage() {}

func (x *GetEdgeScanApplicationTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeScanApplicationTaskResponse.ProtoReflect.Descriptor instead.
func (*GetEdgeScanApplicationTaskResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{43}
}

func (x *GetEdgeScanApplicationTaskResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetEdgeScanApplicationTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEdgeScanApplicationTaskResponse) GetData() *EdgeScanApplicationTask {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_liaison_proto protoreflect.FileDescriptor

const file_liaison_proto_rawDesc = "" +
	"\n" +
	"\rliaison.proto\x1a\x1cgoogle/api/annotations.proto\"\xba\x01\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x16\n" +
	"\x06online\x18\x05 \x01(\x05R\x06online\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\":\n" +
	"\x05Edges\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1b\n" +
	"\x05edges\x18\x02 \x03(\v2\x05.EdgeR\x05edges\"I\n" +
	"\tAccessKey\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\"I\n" +
	"\x11CreateEdgeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"b\n" +
	"\x12CreateEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\x04data\x18\x03 \x01(\v2\n" +
	".AccessKeyR\x04data\" \n" +
	"\x0eGetEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Z\n" +
	"\x0fGetEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x04data\x18\x03 \x01(\v2\x05.EdgeR\x04data\"C\n" +
	"\x10ListEdgesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"]\n" +
	"\x11ListEdgesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\x04data\x18\x03 \x01(\v2\x06.EdgesR\x04data\"q\n" +
	"\x11UpdateEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"]\n" +
	"\x12UpdateEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x04data\x18\x03 \x01(\v2\x05.EdgeR\x04data\"#\n" +
	"\x11DeleteEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"B\n" +
	"\x12DeleteEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf4\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x05R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x05 \x01(\x05R\x06memory\x12\x12\n" +
	"\x04disk\x18\x06 \x01(\x05R\x04disk\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"B\n" +
	"\aDevices\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12!\n" +
	"\adevices\x18\x02 \x03(\v2\a.DeviceR\adevices\"\"\n" +
	"\x10GetDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"^\n" +
	"\x11GetDeviceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\x04data\x18\x03 \x01(\v2\a.DeviceR\x04data\"E\n" +
	"\x12ListDevicesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"a\n" +
	"\x13ListDevicesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\x04data\x18\x03 \x01(\v2\b.DevicesR\x04data\"[\n" +
	"\x13UpdateDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"a\n" +
	"\x14UpdateDeviceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\x04data\x18\x03 \x01(\v2\a.DeviceR\x04data\"\xcb\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x04R\bdeviceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12)\n" +
	"\x10application_type\x18\x05 \x01(\tR\x0fapplicationType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"V\n" +
	"\fApplications\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x120\n" +
	"\fapplications\x18\x02 \x03(\v2\f.ApplicationR\fapplications\"g\n" +
	"\x17ListApplicationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\x04R\bdeviceId\"k\n" +
	"\x18ListApplicationsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x04data\x18\x03 \x01(\v2\r.ApplicationsR\x04data\">\n" +
	"\x18UpdateApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"k\n" +
	"\x19UpdateApplicationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.ApplicationR\x04data\"*\n" +
	"\x18DeleteApplicationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"I\n" +
	"\x19DeleteApplicationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xde\x01\n" +
	"\x05Proxy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\x04R\rapplicationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"A\n" +
	"\aProxies\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12 \n" +
	"\aproxies\x18\x02 \x03(\v2\x06.ProxyR\aproxies\"E\n" +
	"\x12ListProxiesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"a\n" +
	"\x13ListProxiesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\x04data\x18\x03 \x01(\v2\b.ProxiesR\x04data\"\x85\x01\n" +
	"\x12CreateProxyRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"_\n" +
	"\x13CreateProxyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\x04data\x18\x03 \x01(\v2\x06.ProxyR\x04data\"\x86\x01\n" +
	"\x12UpdateProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"_\n" +
	"\x13UpdateProxyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\x04data\x18\x03 \x01(\v2\x06.ProxyR\x04data\"$\n" +
	"\x12DeleteProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"C\n" +
	"\x13DeleteProxyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdb\x01\n" +
	"\x17EdgeScanApplicationTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\x04R\x06edgeId\x12\x1f\n" +
	"\vtask_status\x18\x03 \x01(\tR\n" +
	"taskStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\"\n" +
	"\fapplications\x18\x06 \x03(\tR\fapplications\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"?\n" +
	"$CreateEdgeScanApplicationTaskRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\x04R\x06edgeId\"U\n" +
	"%CreateEdgeScanApplicationTaskResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"!GetEdgeScanApplicationTaskRequest\x12\x17\n" +
	"\aedge_id\x18\x01 \x01(\x04R\x06edgeId\"\x80\x01\n" +
	"\"GetEdgeScanApplicationTaskResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x04data\x18\x03 \x01(\v2\x18.EdgeScanApplicationTaskR\x04data2\xce\f\n" +
	"\x0eLiaisonService\x12K\n" +
	"\n" +
	"CreateEdge\x12\x12.CreateEdgeRequest\x1a\x13.CreateEdgeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/edges\x12D\n" +
	"\aGetEdge\x12\x0f.GetEdgeRequest\x1a\x10.GetEdgeResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/edges/{id}\x12E\n" +
	"\tListEdges\x12\x11.ListEdgesRequest\x1a\x12.ListEdgesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/edges\x12P\n" +
	"\n" +
	"UpdateEdge\x12\x12.UpdateEdgeRequest\x1a\x13.UpdateEdgeResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/edges/{id}\x12M\n" +
	"\n" +
	"DeleteEdge\x12\x12.DeleteEdgeRequest\x1a\x13.DeleteEdgeResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/edges/{id}\x12M\n" +
	"\vListDevices\x12\x13.ListDevicesRequest\x1a\x14.ListDevicesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/devices\x12X\n" +
	"\fUpdateDevice\x12\x14.UpdateDeviceRequest\x1a\x15.UpdateDeviceResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/devices/{id}\x12L\n" +
	"\tGetDevice\x12\x11.GetDeviceRequest\x1a\x12.GetDeviceResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/devices/{id}\x12a\n" +
	"\x10ListApplications\x12\x18.ListApplicationsRequest\x1a\x19.ListApplicationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/applications\x12l\n" +
	"\x11UpdateApplication\x12\x19.UpdateApplicationRequest\x1a\x1a.UpdateApplicationResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/v1/applications/{id}\x12i\n" +
	"\x11DeleteApplication\x12\x19.DeleteApplicationRequest\x1a\x1a.DeleteApplicationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/applications/{id}\x12M\n" +
	"\vListProxies\x12\x13.ListProxiesRequest\x1a\x14.ListProxiesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/proxies\x12P\n" +
	"\vCreateProxy\x12\x13.CreateProxyRequest\x1a\x14.CreateProxyResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/proxies\x12U\n" +
	"\vUpdateProxy\x12\x13.UpdateProxyRequest\x1a\x14.UpdateProxyResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/proxies/{id}\x12R\n" +
	"\vDeleteProxy\x12\x13.DeleteProxyRequest\x1a\x14.DeleteProxyResponse\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/proxies/{id}\x12\xa5\x01\n" +
	"\x1dCreateEdgeScanApplicationTask\x12%.CreateEdgeScanApplicationTaskRequest\x1a&.CreateEdgeScanApplicationTaskResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/edges/{edge_id}/scan_application_tasks\x12\x99\x01\n" +
	"\x1aGetEdgeScanApplicationTask\x12\".GetEdgeScanApplicationTaskRequest\x1a#.GetEdgeScanApplicationTaskResponse\"2\x82\xd3\xe4\x93\x02,\x12*/v1/edges/{edge_id}/scan_application_tasksB'Z%github.com/singchia/liaison/api/v1;v1b\x06proto3"

var (
	file_liaison_proto_rawDescOnce sync.Once
	file_liaison_proto_rawDescData []byte
)

func file_liaison_proto_rawDescGZIP() []byte {
	file_liaison_proto_rawDescOnce.Do(func() {
		file_liaison_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liaison_proto_rawDesc), len(file_liaison_proto_rawDesc)))
	})
	return file_liaison_proto_rawDescData
}

var file_liaison_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_liaison_proto_goTypes = []any{
	(*Edge)(nil),                                  // 0: Edge
	(*Edges)(nil),                                 // 1: Edges
	(*AccessKey)(nil),                             // 2: AccessKey
	(*CreateEdgeRequest)(nil),                     // 3: CreateEdgeRequest
	(*CreateEdgeResponse)(nil),                    // 4: CreateEdgeResponse
	(*GetEdgeRequest)(nil),                        // 5: GetEdgeRequest
	(*GetEdgeResponse)(nil),                       // 6: GetEdgeResponse
	(*ListEdgesRequest)(nil),                      // 7: ListEdgesRequest
	(*ListEdgesResponse)(nil),                     // 8: ListEdgesResponse
	(*UpdateEdgeRequest)(nil),                     // 9: UpdateEdgeRequest
	(*UpdateEdgeResponse)(nil),                    // 10: UpdateEdgeResponse
	(*DeleteEdgeRequest)(nil),                     // 11: DeleteEdgeRequest
	(*DeleteEdgeResponse)(nil),                    // 12: DeleteEdgeResponse
	(*Device)(nil),                                // 13: Device
	(*Devices)(nil),                               // 14: Devices
	(*GetDeviceRequest)(nil),                      // 15: GetDeviceRequest
	(*GetDeviceResponse)(nil),                     // 16: GetDeviceResponse
	(*ListDevicesRequest)(nil),                    // 17: ListDevicesRequest
	(*ListDevicesResponse)(nil),                   // 18: ListDevicesResponse
	(*UpdateDeviceRequest)(nil),                   // 19: UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil),                  // 20: UpdateDeviceResponse
	(*Application)(nil),                           // 21: Application
	(*Applications)(nil),                          // 22: Applications
	(*ListApplicationsRequest)(nil),               // 23: ListApplicationsRequest
	(*ListApplicationsResponse)(nil),              // 24: ListApplicationsResponse
	(*UpdateApplicationRequest)(nil),              // 25: UpdateApplicationRequest
	(*UpdateApplicationResponse)(nil),             // 26: UpdateApplicationResponse
	(*DeleteApplicationRequest)(nil),              // 27: DeleteApplicationRequest
	(*DeleteApplicationResponse)(nil),             // 28: DeleteApplicationResponse
	(*Proxy)(nil),                                 // 29: Proxy
	(*Proxies)(nil),                               // 30: Proxies
	(*ListProxiesRequest)(nil),                    // 31: ListProxiesRequest
	(*ListProxiesResponse)(nil),                   // 32: ListProxiesResponse
	(*CreateProxyRequest)(nil),                    // 33: CreateProxyRequest
	(*CreateProxyResponse)(nil),                   // 34: CreateProxyResponse
	(*UpdateProxyRequest)(nil),                    // 35: UpdateProxyRequest
	(*UpdateProxyResponse)(nil),                   // 36: UpdateProxyResponse
	(*DeleteProxyRequest)(nil),                    // 37: DeleteProxyRequest
	(*DeleteProxyResponse)(nil),                   // 38: DeleteProxyResponse
	(*EdgeScanApplicationTask)(nil),               // 39: EdgeScanApplicationTask
	(*CreateEdgeScanApplicationTaskRequest)(nil),  // 40: CreateEdgeScanApplicationTaskRequest
	(*CreateEdgeScanApplicationTaskResponse)(nil), // 41: CreateEdgeScanApplicationTaskResponse
	(*GetEdgeScanApplicationTaskRequest)(nil),     // 42: GetEdgeScanApplicationTaskRequest
	(*GetEdgeScanApplicationTaskResponse)(nil),    // 43: GetEdgeScanApplicationTaskResponse
}
var file_liaison_proto_depIdxs = []int32{
	0,  // 0: Edges.edges:type_name -> Edge
	2,  // 1: CreateEdgeResponse.data:type_name -> AccessKey
	0,  // 2: GetEdgeResponse.data:type_name -> Edge
	1,  // 3: ListEdgesResponse.data:type_name -> Edges
	0,  // 4: UpdateEdgeResponse.data:type_name -> Edge
	13, // 5: Devices.devices:type_name -> Device
	13, // 6: GetDeviceResponse.data:type_name -> Device
	14, // 7: ListDevicesResponse.data:type_name -> Devices
	13, // 8: UpdateDeviceResponse.data:type_name -> Device
	21, // 9: Applications.applications:type_name -> Application
	22, // 10: ListApplicationsResponse.data:type_name -> Applications
	21, // 11: UpdateApplicationResponse.data:type_name -> Application
	29, // 12: Proxies.proxies:type_name -> Proxy
	30, // 13: ListProxiesResponse.data:type_name -> Proxies
	29, // 14: CreateProxyResponse.data:type_name -> Proxy
	29, // 15: UpdateProxyResponse.data:type_name -> Proxy
	39, // 16: GetEdgeScanApplicationTaskResponse.data:type_name -> EdgeScanApplicationTask
	3,  // 17: LiaisonService.CreateEdge:input_type -> CreateEdgeRequest
	5,  // 18: LiaisonService.GetEdge:input_type -> GetEdgeRequest
	7,  // 19: LiaisonService.ListEdges:input_type -> ListEdgesRequest
	9,  // 20: LiaisonService.UpdateEdge:input_type -> UpdateEdgeRequest
	11, // 21: LiaisonService.DeleteEdge:input_type -> DeleteEdgeRequest
	17, // 22: LiaisonService.ListDevices:input_type -> ListDevicesRequest
	19, // 23: LiaisonService.UpdateDevice:input_type -> UpdateDeviceRequest
	15, // 24: LiaisonService.GetDevice:input_type -> GetDeviceRequest
	23, // 25: LiaisonService.ListApplications:input_type -> ListApplicationsRequest
	25, // 26: LiaisonService.UpdateApplication:input_type -> UpdateApplicationRequest
	27, // 27: LiaisonService.DeleteApplication:input_type -> DeleteApplicationRequest
	31, // 28: LiaisonService.ListProxies:input_type -> ListProxiesRequest
	33, // 29: LiaisonService.CreateProxy:input_type -> CreateProxyRequest
	35, // 30: LiaisonService.UpdateProxy:input_type -> UpdateProxyRequest
	37, // 31: LiaisonService.DeleteProxy:input_type -> DeleteProxyRequest
	40, // 32: LiaisonService.CreateEdgeScanApplicationTask:input_type -> CreateEdgeScanApplicationTaskRequest
	42, // 33: LiaisonService.GetEdgeScanApplicationTask:input_type -> GetEdgeScanApplicationTaskRequest
	4,  // 34: LiaisonService.CreateEdge:output_type -> CreateEdgeResponse
	6,  // 35: LiaisonService.GetEdge:output_type -> GetEdgeResponse
	8,  // 36: LiaisonService.ListEdges:output_type -> ListEdgesResponse
	10, // 37: LiaisonService.UpdateEdge:output_type -> UpdateEdgeResponse
	12, // 38: LiaisonService.DeleteEdge:output_type -> DeleteEdgeResponse
	18, // 39: LiaisonService.ListDevices:output_type -> ListDevicesResponse
	20, // 40: LiaisonService.UpdateDevice:output_type -> UpdateDeviceResponse
	16, // 41: LiaisonService.GetDevice:output_type -> GetDeviceResponse
	24, // 42: LiaisonService.ListApplications:output_type -> ListApplicationsResponse
	26, // 43: LiaisonService.UpdateApplication:output_type -> UpdateApplicationResponse
	28, // 44: LiaisonService.DeleteApplication:output_type -> DeleteApplicationResponse
	32, // 45: LiaisonService.ListProxies:output_type -> ListProxiesResponse
	34, // 46: LiaisonService.CreateProxy:output_type -> CreateProxyResponse
	36, // 47: LiaisonService.UpdateProxy:output_type -> UpdateProxyResponse
	38, // 48: LiaisonService.DeleteProxy:output_type -> DeleteProxyResponse
	41, // 49: LiaisonService.CreateEdgeScanApplicationTask:output_type -> CreateEdgeScanApplicationTaskResponse
	43, // 50: LiaisonService.GetEdgeScanApplicationTask:output_type -> GetEdgeScanApplicationTaskResponse
	34, // [34:51] is the sub-list for method output_type
	17, // [17:34] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_liaison_proto_init() }
func file_liaison_proto_init() {
	if File_liaison_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liaison_proto_rawDesc), len(file_liaison_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_liaison_proto_goTypes,
		DependencyIndexes: file_liaison_proto_depIdxs,
		MessageInfos:      file_liaison_proto_msgTypes,
	}.Build()
	File_liaison_proto = out.File
	file_liaison_proto_goTypes = nil
	file_liaison_proto_depIdxs = nil
}
