// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: liaison.proto

package liaison

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_liaison_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{0}
}

func (x *Edge) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Edge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Edge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Edge) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Edge) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Edge) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AccessKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_liaison_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKey.ProtoReflect.Descriptor instead.
func (*AccessKey) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{1}
}

func (x *AccessKey) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *AccessKey) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

// 创建边缘节点请求
type CreateEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeRequest) Reset() {
	*x = CreateEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeRequest) ProtoMessage() {}

func (x *CreateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEdgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEdgeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AccessKey             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeResponse) Reset() {
	*x = CreateEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeResponse) ProtoMessage() {}

func (x *CreateEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeResponse.ProtoReflect.Descriptor instead.
func (*CreateEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateEdgeResponse) GetData() *AccessKey {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取边缘节点请求
type GetEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeRequest) Reset() {
	*x = GetEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeRequest) ProtoMessage() {}

func (x *GetEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeRequest.ProtoReflect.Descriptor instead.
func (*GetEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{4}
}

func (x *GetEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Edge                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgeResponse) Reset() {
	*x = GetEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgeResponse) ProtoMessage() {}

func (x *GetEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgeResponse.ProtoReflect.Descriptor instead.
func (*GetEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{5}
}

func (x *GetEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEdgeResponse) GetData() *Edge {
	if x != nil {
		return x.Data
	}
	return nil
}

// 列举边缘节点请求
type ListEdgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEdgesRequest) Reset() {
	*x = ListEdgesRequest{}
	mi := &file_liaison_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEdgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEdgesRequest) ProtoMessage() {}

func (x *ListEdgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEdgesRequest.ProtoReflect.Descriptor instead.
func (*ListEdgesRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{6}
}

func (x *ListEdgesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEdgesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEdgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*Edge                `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEdgesResponse) Reset() {
	*x = ListEdgesResponse{}
	mi := &file_liaison_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEdgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEdgesResponse) ProtoMessage() {}

func (x *ListEdgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEdgesResponse.ProtoReflect.Descriptor instead.
func (*ListEdgesResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{7}
}

func (x *ListEdgesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListEdgesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListEdgesResponse) GetData() []*Edge {
	if x != nil {
		return x.Data
	}
	return nil
}

// 更新边缘节点请求
type UpdateEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"` // 1: running, 2: stopped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEdgeRequest) Reset() {
	*x = UpdateEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEdgeRequest) ProtoMessage() {}

func (x *UpdateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEdgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEdgeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEdgeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEdgeRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Edge                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEdgeResponse) Reset() {
	*x = UpdateEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEdgeResponse) ProtoMessage() {}

func (x *UpdateEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEdgeResponse.ProtoReflect.Descriptor instead.
func (*UpdateEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateEdgeResponse) GetData() *Edge {
	if x != nil {
		return x.Data
	}
	return nil
}

// 删除边缘节点请求
type DeleteEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeRequest) Reset() {
	*x = DeleteEdgeRequest{}
	mi := &file_liaison_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeRequest) ProtoMessage() {}

func (x *DeleteEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEdgeRequest) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteEdgeRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeResponse) Reset() {
	*x = DeleteEdgeResponse{}
	mi := &file_liaison_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeResponse) ProtoMessage() {}

func (x *DeleteEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liaison_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteEdgeResponse) Descriptor() ([]byte, []int) {
	return file_liaison_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEdgeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteEdgeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_liaison_proto protoreflect.FileDescriptor

const file_liaison_proto_rawDesc = "" +
	"\n" +
	"\rliaison.proto\x1a\x1cgoogle/api/annotations.proto\"\xa2\x01\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"I\n" +
	"\tAccessKey\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\"I\n" +
	"\x11CreateEdgeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"b\n" +
	"\x12CreateEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\x04data\x18\x03 \x01(\v2\n" +
	".AccessKeyR\x04data\" \n" +
	"\x0eGetEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Z\n" +
	"\x0fGetEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x04data\x18\x03 \x01(\v2\x05.EdgeR\x04data\"C\n" +
	"\x10ListEdgesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\\\n" +
	"\x11ListEdgesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x04data\x18\x03 \x03(\v2\x05.EdgeR\x04data\"q\n" +
	"\x11UpdateEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"]\n" +
	"\x12UpdateEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\x04data\x18\x03 \x01(\v2\x05.EdgeR\x04data\"#\n" +
	"\x11DeleteEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"B\n" +
	"\x12DeleteEdgeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8b\x03\n" +
	"\x0eLiaisonService\x12K\n" +
	"\n" +
	"CreateEdge\x12\x12.CreateEdgeRequest\x1a\x13.CreateEdgeResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/edges\x12D\n" +
	"\aGetEdge\x12\x0f.GetEdgeRequest\x1a\x10.GetEdgeResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/edges/{id}\x12E\n" +
	"\tListEdges\x12\x11.ListEdgesRequest\x1a\x12.ListEdgesResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/edges\x12P\n" +
	"\n" +
	"UpdateEdge\x12\x12.UpdateEdgeRequest\x1a\x13.UpdateEdgeResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/edges/{id}\x12M\n" +
	"\n" +
	"DeleteEdge\x12\x12.DeleteEdgeRequest\x1a\x13.DeleteEdgeResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/edges/{id}B,Z*github.com/singchia/liaison/api/v1;liaisonb\x06proto3"

var (
	file_liaison_proto_rawDescOnce sync.Once
	file_liaison_proto_rawDescData []byte
)

func file_liaison_proto_rawDescGZIP() []byte {
	file_liaison_proto_rawDescOnce.Do(func() {
		file_liaison_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liaison_proto_rawDesc), len(file_liaison_proto_rawDesc)))
	})
	return file_liaison_proto_rawDescData
}

var file_liaison_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_liaison_proto_goTypes = []any{
	(*Edge)(nil),               // 0: Edge
	(*AccessKey)(nil),          // 1: AccessKey
	(*CreateEdgeRequest)(nil),  // 2: CreateEdgeRequest
	(*CreateEdgeResponse)(nil), // 3: CreateEdgeResponse
	(*GetEdgeRequest)(nil),     // 4: GetEdgeRequest
	(*GetEdgeResponse)(nil),    // 5: GetEdgeResponse
	(*ListEdgesRequest)(nil),   // 6: ListEdgesRequest
	(*ListEdgesResponse)(nil),  // 7: ListEdgesResponse
	(*UpdateEdgeRequest)(nil),  // 8: UpdateEdgeRequest
	(*UpdateEdgeResponse)(nil), // 9: UpdateEdgeResponse
	(*DeleteEdgeRequest)(nil),  // 10: DeleteEdgeRequest
	(*DeleteEdgeResponse)(nil), // 11: DeleteEdgeResponse
}
var file_liaison_proto_depIdxs = []int32{
	1,  // 0: CreateEdgeResponse.data:type_name -> AccessKey
	0,  // 1: GetEdgeResponse.data:type_name -> Edge
	0,  // 2: ListEdgesResponse.data:type_name -> Edge
	0,  // 3: UpdateEdgeResponse.data:type_name -> Edge
	2,  // 4: LiaisonService.CreateEdge:input_type -> CreateEdgeRequest
	4,  // 5: LiaisonService.GetEdge:input_type -> GetEdgeRequest
	6,  // 6: LiaisonService.ListEdges:input_type -> ListEdgesRequest
	8,  // 7: LiaisonService.UpdateEdge:input_type -> UpdateEdgeRequest
	10, // 8: LiaisonService.DeleteEdge:input_type -> DeleteEdgeRequest
	3,  // 9: LiaisonService.CreateEdge:output_type -> CreateEdgeResponse
	5,  // 10: LiaisonService.GetEdge:output_type -> GetEdgeResponse
	7,  // 11: LiaisonService.ListEdges:output_type -> ListEdgesResponse
	9,  // 12: LiaisonService.UpdateEdge:output_type -> UpdateEdgeResponse
	11, // 13: LiaisonService.DeleteEdge:output_type -> DeleteEdgeResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_liaison_proto_init() }
func file_liaison_proto_init() {
	if File_liaison_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liaison_proto_rawDesc), len(file_liaison_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_liaison_proto_goTypes,
		DependencyIndexes: file_liaison_proto_depIdxs,
		MessageInfos:      file_liaison_proto_msgTypes,
	}.Build()
	File_liaison_proto = out.File
	file_liaison_proto_goTypes = nil
	file_liaison_proto_depIdxs = nil
}
